# Generated by Django 5.1.3 on 2024-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlfaBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250, verbose_name='Логин API')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль API')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
