# Generated by Django 5.1.3 on 2024-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews', verbose_name='Аватар пользователя')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('text', models.TextField(blank=True, max_length=250, null=True, verbose_name='Текст отзыва')),
                ('status', models.BooleanField(default=False, verbose_name='Статус публикации')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ('-id',),
            },
        ),
    ]
