# Generated by Django 5.1.3 on 2024-12-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('phone', models.CharField(blank=True, default=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('requires_delivery', models.BooleanField(blank=True, null=True, verbose_name='Нужна доставка ?')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID платежа')),
                ('payment_dop_info', models.CharField(blank=True, max_length=550, null=True, verbose_name='Информация о платеже (ссылка на плптеж)')),
                ('pay_method', models.CharField(blank=True, max_length=250, null=True, verbose_name='Способ оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено ?')),
                ('summ', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма платежа')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Не говорить от кого')),
                ('surprise', models.BooleanField(default=False, verbose_name='Не предупреждать получателя')),
                ('first_name_human', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя получателя')),
                ('phone_number_human', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер получателя')),
                ('pickup', models.BooleanField(default=False, verbose_name='Самовывоз')),
                ('who_get_bouqets', models.BooleanField(default=False, verbose_name='Кто получатель ?')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('selected_char', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Проданный товара',
                'verbose_name_plural': 'Проданные товары',
                'db_table': 'order_item',
            },
        ),
    ]
