# Generated by Django 5.1.3 on 2024-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Название статьи')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержимое статьи')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Изображение статьи')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Изображение баннера')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст на странице')),
            ],
        ),
    ]
