# Generated by Django 3.2.25 on 2026-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Первый текст')),
                ('description_two', models.TextField(blank=True, null=True, verbose_name='Второй текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Изображение')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='base-settings', verbose_name='Логотип')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='base-settings', verbose_name='Логотип Темный')),
                ('logo_width', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Ширина')),
                ('logo_height', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Высота')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('time_work', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Время работы')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='base-settings/', verbose_name='ФавИконка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_page', models.BooleanField(default=False, verbose_name='Включить страницу')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Код карты')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст на странице')),
                ('description_two', models.TextField(blank=True, null=True, verbose_name='Второй текст на странице')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-image', verbose_name='Фотография')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование пойдет в alt и title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить на сайт ?')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='')),
                ('home_view', models.BooleanField(default=False, verbose_name='Отображать на главной ?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-category', verbose_name='Фотография категории')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='home-page', verbose_name='Картинка главной страницы')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('sale_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст скидки в всплывающем окне')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('sale_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст скидки в всплывающем окне')),
            ],
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nDisallow: /admin/')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Офис продаж Максимум', max_length=250, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона')),
                ('time_work', models.CharField(blank=True, default='Вт-сб 09:00-18:00, Вс-пн выходной', max_length=250, null=True, verbose_name='Режим работы')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('validity', models.DateTimeField(blank=True, help_text='После окончания акции, она перейдет в состояние не активна', null=True, verbose_name='Срок дейстия акции')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock', verbose_name='ФОтография акции')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('slider_status', models.BooleanField(default=False, verbose_name='Слайдер на главной')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-image', verbose_name='Фотография')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Минимальный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить на сайт ?')),
            ],
        ),
    ]
