# Generated by Django 5.1.3 on 2024-11-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='base-settings', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('time_work', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Время работы')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='base-settings/', verbose_name='ФавИконка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='')),
                ('home_view', models.BooleanField(default=False, verbose_name='Отображать на главной ?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-category', verbose_name='Фотография категории')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='home-page', verbose_name='Картинка главной страницы')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nDisallow: /admin/')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('validity', models.DateTimeField(blank=True, help_text='После окончания акции, она перейдет в состояние не активна', null=True, verbose_name='Срок дейстия акции')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock', verbose_name='ФОтография акции')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('slider_status', models.BooleanField(default=False, verbose_name='Слайдер на главной')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-image', verbose_name='Фотография')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование пойдет в alt и title')),
                ('cat_detail', models.BooleanField(default=False, verbose_name='Вывод в категорию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить на сайт ?')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.gallerycategory')),
            ],
        ),
    ]
