# Generated by Django 5.1.3 on 2025-05-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Первый текст')),
                ('description_two', models.TextField(blank=True, null=True, verbose_name='Второй текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Изображение')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
    ]
