# Generated by Django 5.1.3 on 2025-05-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='cat_detail',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
    ]
