# Generated by Django 5.1.3 on 2025-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gallery_cat_detail_remove_gallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст на странице'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='meta_title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок'),
        ),
    ]
