# Generated by Django 5.1.3 on 2025-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_gallery_image_remove_gallery_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст на странице')),
                ('meta_h1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_h1',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery-image', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Выводить на сайт ?'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование пойдет в alt и title'),
        ),
    ]
