# Generated by Django 5.1.3 on 2025-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delivery_description_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона')),
                ('time_work', models.CharField(blank=True, max_length=250, null=True, verbose_name='Режим работы')),
            ],
        ),
    ]
