# Generated by Django 5.1.3 on 2025-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_salesoffices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoffices',
            name='name',
            field=models.CharField(blank=True, default='Офис продаж Максимум', max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='salesoffices',
            name='time_work',
            field=models.CharField(blank=True, default='Вт-сб 09:00-18:00, Вс-пн выходной', max_length=250, null=True, verbose_name='Режим работы'),
        ),
    ]
