# Generated by Django 3.2.25 on 2025-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_salesoffices_name_alter_salesoffices_time_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_page', models.BooleanField(default=False, verbose_name='Включить страницу')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Код карты')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
