# Generated by Django 3.2.25 on 2025-06-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contacttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-image', verbose_name='Фотография')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Минимальный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить на сайт ?')),
            ],
        ),
    ]
