# Generated by Django 3.2.25 on 2025-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometemplate',
            name='sale_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст скидки в всплывающем окне'),
        ),
        migrations.AddField(
            model_name='production',
            name='sale_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст скидки в всплывающем окне'),
        ),
    ]
