# Generated by Django 3.2.25 on 2025-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20250626_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='base-settings', verbose_name='Логотип Темный'),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='logo_height',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='logo_width',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Ширина'),
        ),
    ]
