# Generated by Django 3.2.25 on 2026-03-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_image', verbose_name='Изображение категории')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='META заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='META описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='META keywords')),
                ('add_menu', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выводить в меню ? ')),
                ('sale_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст скидки в всплывающем окне')),
                ('name_btn', models.CharField(choices=[('price', 'Узнать цену'), ('more', 'Оставить заявку')], default='more', max_length=20, verbose_name='Текст кнопки в карточке товара')),
                ('view_price', models.CharField(choices=[('view', 'Показать цену'), ('no', 'Не показывать цену')], default='view', max_length=20, verbose_name='Показывать цену в карточке товара')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Дочерняя категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Название цвета')),
                ('code_color', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Код цвета')),
                ('image_color', models.ImageField(blank=True, null=True, upload_to='product_color', verbose_name='Изображение цвета')),
                ('active', models.BooleanField(default=True, verbose_name='Выводить на сайте')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('manufacturer', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Производитель')),
                ('manufacturer_description', models.TextField(blank=True, null=True, verbose_name='Описание производителя')),
                ('colors', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цветовая схема')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_iamge', verbose_name='Изображение товара')),
                ('price', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Цена')),
                ('installment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Рассрочка')),
                ('sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('quantity_purchase', models.IntegerField(default=0, verbose_name='Количество купленных')),
                ('status', models.BooleanField(default=True, verbose_name='Опубликовать ?')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='related_products', to='shop.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня')),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='META заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='META описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='META keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название характеристки')),
                ('value', models.CharField(blank=True, max_length=250, null=True, verbose_name='Значение характеристки')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='shop.product', verbose_name='Родитель')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='product_iamge', verbose_name='Дополнительны изображения')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Привязка к продукту')),
            ],
            options={
                'verbose_name': 'Изображение',
            },
        ),
    ]
