# Generated by Django 5.1.3 on 2025-01-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='META заголовок'),
        ),
    ]
