# Generated by Django 5.1.3 on 2025-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Мета заголовок'),
        ),
    ]
