# Generated by Django 5.1.3 on 2025-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='META заголовок'),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='code_color',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='META заголовок'),
        ),
    ]
