# Generated by Django 5.1.3 on 2024-12-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название поддомена')),
                ('geotag', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГеоТег')),
                ('subdomain', models.CharField(max_length=255, unique=True, verbose_name='Субдомен')),
            ],
        ),
        migrations.CreateModel(
            name='SubdomainContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('phone_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй номер телефона')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='subdomain.subdomain', verbose_name='Привязка к субдомену')),
            ],
        ),
    ]
