# Generated by Django 5.1.3 on 2024-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Изображение услуги')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Текст под заголвком')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('meta_title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
            ],
        ),
    ]
