# Generated by Django 5.1.3 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета h1'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='meta_h1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Мета h1'),
        ),
    ]
