# Generated by Django 5.1.3 on 2025-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_meta_h1_servicepage_meta_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое статьи'),
        ),
    ]
