# Generated by Django 5.1.3 on 2025-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_subtitle_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='footer_view',
            field=models.BooleanField(default=True, verbose_name='Выводить в футер'),
        ),
    ]
